name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psutil

    - name: Run system health script
      run: python system_health.py

    - name: Run log parser script
      run: python log_parser.py || echo "No log file found"

    - name: Dummy Deployment Step
      run: echo "✅ Deployment Success!"
